include: package:lints/recommended.yaml

linter:
  rules:
    require_trailing_commas: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
