name: ttpolyglot_model
description: TTPolyglot 模型包，提供翻译管理平台的数据模型
version: 1.0.0
publish_to: none 

environment:
  sdk: ^3.6.1

dependencies:
  # Freezed 数据类
  freezed_annotation: ^2.4.0
  json_annotation: ^4.9.0
  
  # SharedPreferences
  shared_preferences: ^2.3.5

dev_dependencies:
  # Flutter 依赖
  flutter:
    sdk: flutter
  
  # 代码生成
  build_runner: ^2.4.0
  freezed: ^2.5.0
  json_serializable: ^6.8.0
  
  # 代码质量检查
  flutter_lints: ^5.0.0

  # 单元测试
  flutter_test:
    sdk: flutter
