name: ttpolyglot_translators
description: TTPolyglot 翻译服务集成（Google、百度、腾讯等）
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  crypto: ^3.0.3
  ttpolyglot_model: ^1.0.0

dev_dependencies:
  test: ^1.24.9
  lints: ^5.0.0
