name: ttpolyglot_server
description: "TTPolyglot 多语言翻译管理系统 - 服务端"
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  # 内部包依赖
  ttpolyglot_model: ^1.0.0
  
  # HTTP 服务器框架
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  
  # 数据库相关
  drift: ^2.14.1
  postgres: ^3.0.2
  drift_postgres: ^1.1.0
  sqlite3: ^2.4.0
  
  # Redis 缓存
  redis: ^3.1.0
  
  # JWT 身份验证
  dart_jsonwebtoken: ^2.12.1
  
  # 加密和安全
  crypto: ^3.0.3
  bcrypt: ^1.1.3
  
  # 环境变量配置
  dotenv: ^4.2.0
  
  # JSON 序列化
  json_annotation: ^4.8.1
  
  # 日志记录
  logging: ^1.2.0
  
  # HTTP 客户端（用于外部API调用）
  http: ^1.1.2
  
  # 数据验证
  validators: ^3.0.0
  
  # 文件处理
  mime: ^1.0.4
  path: ^1.8.3
  
  # 时间处理
  timezone: ^0.9.2
  
  # UUID 生成
  uuid: ^4.2.1
  
  # 邮件发送 (可选)
  mailer: ^6.0.1

dev_dependencies:
  # 测试框架
  test: ^1.24.9
  mockito: ^5.4.4
  
  # 代码生成
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1
  
  # 代码分析
  lints: ^5.0.0
  
  # 测试覆盖率
  coverage: ^1.7.1

# 可执行文件配置
executables:
  server: