name: ttpolyglot
description: TTPolyglot 翻译管理平台 - 支持桌面、Web、移动端的统一应用
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

  # 核心依赖
  ttpolyglot_core: ^1.0.0
  ttpolyglot_parsers: ^1.0.0

  # UI 框架
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2762.0

  # 路由管理
  go_router: ^14.2.7

  # 状态管理
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

  # 平台检测
  universal_platform: ^1.1.0

  # 文件系统操作 (桌面端)
  path_provider: ^2.1.4
  file_picker: ^8.1.2

  # Web 存储 (Web端)
  shared_preferences: ^2.3.2

  # 窗口管理 (桌面端)
  window_manager: ^0.4.2

  # 系统托盘 (桌面端)
  tray_manager: ^0.2.3

  # 热键支持 (桌面端)
  hotkey_manager: ^0.2.3

  # 文件监控 (桌面端)
  watcher: ^1.1.0

  # HTTP 客户端
  http: ^1.2.2
  dio: ^5.7.0

  # JSON 处理
  json_annotation: ^4.8.1

  # 国际化
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # 主题和样式
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1

  # 工具库
  uuid: ^4.5.1
  collection: ^1.18.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 代码生成
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  # 测试工具
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # 资源文件
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/fonts/

  # # 字体配置
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
