name: ttpolyglot
description: TTPolyglot 翻译管理平台 - 支持桌面、Web、移动端的统一应用
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.6.1
  flutter: 3.27.3

dependencies:
  archive: ^3.6.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  csv: ^6.0.0
  excel: ^2.1.0
  file_picker: ^8.1.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  hotkey_manager: ^0.2.3
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  material_symbols_icons: ^4.2762.0
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  tray_manager: ^0.2.3
  ttpolyglot_core: ^1.0.0
  ttpolyglot_parsers: ^1.0.0
  universal_platform: ^1.1.0
  uuid: ^4.5.1
  watcher: ^1.1.0
  window_manager: ^0.4.2

dev_dependencies:
  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  rename_app: ^1.6.3

flutter:
  uses-material-design: true
  # 资源文件
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/fonts/
  # # 字体配置
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
