name: ttpolyglot_utils
description: "TTPolyglot 多语言翻译管理系统 - 工具类"
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Talker 日志系统
  talker_flutter: ^4.7.1
  talker_dio_logger: ^4.7.1

  # Toast 提示组件
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
